### ISSUE TITLE
Deprecation in favor of prometheus/blackbox_exporter?

### ISSUE THREAD

**Issue by discordianfish** [discordianfish/blackbox_prober#5]
After I created this repo, @brian-brazil created https://github.com/prometheus/blackbox_exporter which has the main advantage that it doesn't require configuration changes to add new targets.
The only disadvantage I see is that it only supports metric exposition via the text protocol but I don't think that's an big issue.

So is anyone using this blackbox_prober who can't/don't want to use the blackbox_exporter? If so, please let us know why so we can potentially fix those issues and/or extend the blackbox_exporter.

**Comment by brian-brazil** [comment]
It might be wise to wait until the next Prometheus release, as that has some tweaks to make using prometheus/blackbox_exporter easier.

**Comment by discordianfish** [comment]
@brian-brazil :+1: sounds good! I've added a deprecation warning to the code for now and will wait for the next prometheus release before doing anything further.
